
for session = 1:29
    nSSDs = length(executiveBeh.inh_SSD{session});
    ttx_noncanc.left{session} = [];
    ttx_noncanc.right{session} = [];
    
    for ssdIdx = 1:nSSDs
        ttx_noncanc.left{session} = [ttx_noncanc.left{session}; executiveBeh.ttm_c.NC{session,ssdIdx}.left];
        ttx_noncanc.right{session} = [ttx_noncanc.right{session}; executiveBeh.ttm_c.NC{session,ssdIdx}.right];
    end
    
    ttx_noncanc.left{session} = sort(ttx_noncanc.left{session});
    ttx_noncanc.right{session} = sort(ttx_noncanc.right{session});
    
end


stoppingBeta.errorLateralisation.left = SEF_stoppingLFP_getAverageBurstTimeError...
    (corticalLFPcontacts.all,ttx_noncanc.left, sessionLFPmap, [300 600]);
stoppingBeta.errorLateralisation.right = SEF_stoppingLFP_getAverageBurstTimeError...
    (corticalLFPcontacts.all,ttx_noncanc.right, sessionLFPmap, [300 600]);





[mean(stoppingBeta.errorLateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu)),...
    sem(stoppingBeta.errorLateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu));...
nanmean(stoppingBeta.errorLateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu)),...
sem(stoppingBeta.errorLateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu))]*100

[h, p, ~, stats] = ttest(stoppingBeta.errorLateralisation.left.pTrials_burst(corticalLFPcontacts.subset.x),...
    stoppingBeta.errorLateralisation.right.pTrials_burst(corticalLFPcontacts.subset.x))

figure('Renderer', 'painters', 'Position', [100 100 350 350]);
scatter(stoppingBeta.errorLateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu),...
    stoppingBeta.errorLateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu),'s')
hold on;
scatter(stoppingBeta.errorLateralisation.left.pTrials_burst(corticalLFPcontacts.subset.x),...
    stoppingBeta.errorLateralisation.right.pTrials_burst(corticalLFPcontacts.subset.x),'^')
hold on; plot([-0.1:0.01:0.6],[-0.10:0.01:0.6],'k');

errorbar(mean(stoppingBeta.errorLateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu)),...
    mean(stoppingBeta.errorLateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu)),...
    std(stoppingBeta.errorLateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu))*2,...
    std(stoppingBeta.errorLateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu))*2,...
    std(stoppingBeta.errorLateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu))*2,...
    std(stoppingBeta.errorLateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu))*2,'ko') 

errorbar(mean(stoppingBeta.errorLateralisation.left.pTrials_burst(corticalLFPcontacts.subset.x)),...
    mean(stoppingBeta.errorLateralisation.right.pTrials_burst(corticalLFPcontacts.subset.x)),...
    std(stoppingBeta.errorLateralisation.right.pTrials_burst(corticalLFPcontacts.subset.x))*2,...
    std(stoppingBeta.errorLateralisation.right.pTrials_burst(corticalLFPcontacts.subset.x))*2,...
    std(stoppingBeta.errorLateralisation.left.pTrials_burst(corticalLFPcontacts.subset.x))*2,...
    std(stoppingBeta.errorLateralisation.left.pTrials_burst(corticalLFPcontacts.subset.x))*2,'ko') 

xlim([-0 0.6]); ylim([-0 0.6])