
for session = 1:29
    nSSDs = length(executiveBeh.inh_SSD{session});
    ttx_canc.left{session} = [];
    ttx_canc.right{session} = [];
    
    for ssdIdx = 1:nSSDs
        ttx_canc.left{session} = [ttx_canc.left{session}; executiveBeh.ttm_c.C{session,ssdIdx}.left];
        ttx_canc.right{session} = [ttx_canc.right{session}; executiveBeh.ttm_c.C{session,ssdIdx}.right];
    end
    
    ttx_canc.left{session} = sort(ttx_canc.left{session});
    ttx_canc.right{session} = sort(ttx_canc.right{session});
    
end


stoppingBeta.lateralisation.left = SEF_stoppingLFP_getAverageBurstTime...
    (corticalLFPcontacts.all,ttx_canc.left, bayesianSSRT, sessionLFPmap);
stoppingBeta.lateralisation.right = SEF_stoppingLFP_getAverageBurstTime...
    (corticalLFPcontacts.all,ttx_canc.right, bayesianSSRT, sessionLFPmap);

[mean(stoppingBeta.lateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu)),...
    sem(stoppingBeta.lateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu));...
nanmean(stoppingBeta.lateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu)),...
sem(stoppingBeta.lateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu))]*100

ttest(stoppingBeta.lateralisation.left.pTrials_burst(corticalLFPcontacts.subset.x),...
    stoppingBeta.lateralisation.right.pTrials_burst(corticalLFPcontacts.subset.x))

figure('Renderer', 'painters', 'Position', [100 100 350 350]);
scatter(stoppingBeta.lateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu),...
    stoppingBeta.lateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu),'s')
hold on;
scatter(stoppingBeta.lateralisation.left.pTrials_burst(corticalLFPcontacts.subset.x),...
    stoppingBeta.lateralisation.right.pTrials_burst(corticalLFPcontacts.subset.x),'^')
hold on; plot([-0.1:0.01:0.35],[-0.10:0.01:0.35],'k');

errorbar(mean(stoppingBeta.lateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu)),...
    mean(stoppingBeta.lateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu)),...
    std(stoppingBeta.lateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu))*2,...
    std(stoppingBeta.lateralisation.right.pTrials_burst(corticalLFPcontacts.subset.eu))*2,...
    std(stoppingBeta.lateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu))*2,...
    std(stoppingBeta.lateralisation.left.pTrials_burst(corticalLFPcontacts.subset.eu))*2,'ko') 

errorbar(mean(stoppingBeta.lateralisation.left.pTrials_burst(corticalLFPcontacts.subset.x)),...
    mean(stoppingBeta.lateralisation.right.pTrials_burst(corticalLFPcontacts.subset.x)),...
    std(stoppingBeta.lateralisation.right.pTrials_burst(corticalLFPcontacts.subset.x))*2,...
    std(stoppingBeta.lateralisation.right.pTrials_burst(corticalLFPcontacts.subset.x))*2,...
    std(stoppingBeta.lateralisation.left.pTrials_burst(corticalLFPcontacts.subset.x))*2,...
    std(stoppingBeta.lateralisation.left.pTrials_burst(corticalLFPcontacts.subset.x))*2,'ko') 

xlim([-0.1 0.35]); ylim([-0.1 0.35])