corticalLFPmap = sessionLFPmap(sessionLFPmap.cortexFlag == 1,:); 

clear g
EuContacts = find(corticalLFPmap.monkeyFlag == 0);
xContacts = find(corticalLFPmap.monkeyFlag == 1);

g(1,1)=gramm('x',[stoppingBeta.timing.canceled.mean_burstOnset;...
    stoppingBeta.timing.canceled.mean_burstTime;...
    stoppingBeta.timing.canceled.mean_burstOffset],'color',...
    [repmat({'Onset'},509,1);repmat({'Peak'},509,1);repmat({'Offset'},509,1)]);

g(2,1)=gramm('x',[stoppingBeta.timing.nostop.mean_burstOnset;...
    stoppingBeta.timing.nostop.mean_burstTime;...
    stoppingBeta.timing.nostop.mean_burstOffset],'color',...
    [repmat({'Onset'},509,1);repmat({'Peak'},509,1);repmat({'Offset'},509,1)]);

g(3,1)=gramm('x',[stoppingBeta.timing.noncanceled.mean_burstOnset;...
    stoppingBeta.timing.noncanceled.mean_burstTime;...
    stoppingBeta.timing.noncanceled.mean_burstOffset],'color',...
    [repmat({'Onset'},509,1);repmat({'Peak'},509,1);repmat({'Offset'},509,1)]);

% Eu only
g(1,2)=gramm('x',[stoppingBeta.timing.canceled.mean_burstOnset(EuContacts);...
    stoppingBeta.timing.canceled.mean_burstTime(EuContacts);...
    stoppingBeta.timing.canceled.mean_burstOffset(EuContacts)],'color',...
    [repmat({'Onset'},length(EuContacts),1);repmat({'Peak'},length(EuContacts),1);repmat({'Offset'},length(EuContacts),1)]);

g(2,2)=gramm('x',[stoppingBeta.timing.nostop.mean_burstOnset(EuContacts);...
    stoppingBeta.timing.nostop.mean_burstTime(EuContacts);...
    stoppingBeta.timing.nostop.mean_burstOffset(EuContacts)],'color',...
    [repmat({'Onset'},length(EuContacts),1);repmat({'Peak'},length(EuContacts),1);repmat({'Offset'},length(EuContacts),1)]);

g(3,2)=gramm('x',[stoppingBeta.timing.noncanceled.mean_burstOnset(EuContacts);...
    stoppingBeta.timing.noncanceled.mean_burstTime(EuContacts);...
    stoppingBeta.timing.noncanceled.mean_burstOffset(EuContacts)],'color',...
    [repmat({'Onset'},length(EuContacts),1);repmat({'Peak'},length(EuContacts),1);repmat({'Offset'},length(EuContacts),1)]);

% X only
g(1,3)=gramm('x',[stoppingBeta.timing.canceled.mean_burstOnset(xContacts);...
    stoppingBeta.timing.canceled.mean_burstTime(xContacts);...
    stoppingBeta.timing.canceled.mean_burstOffset(xContacts)],'color',...
    [repmat({'Onset'},length(xContacts),1);repmat({'Peak'},length(xContacts),1);repmat({'Offset'},length(xContacts),1)]);

g(2,3)=gramm('x',[stoppingBeta.timing.nostop.mean_burstOnset(xContacts);...
    stoppingBeta.timing.nostop.mean_burstTime(xContacts);...
    stoppingBeta.timing.nostop.mean_burstOffset(xContacts)],'color',...
    [repmat({'Onset'},length(xContacts),1);repmat({'Peak'},length(xContacts),1);repmat({'Offset'},length(xContacts),1)]);

g(3,3)=gramm('x',[stoppingBeta.timing.noncanceled.mean_burstOnset(xContacts);...
    stoppingBeta.timing.noncanceled.mean_burstTime(xContacts);...
    stoppingBeta.timing.noncanceled.mean_burstOffset(xContacts)],'color',...
    [repmat({'Onset'},length(xContacts),1);repmat({'Peak'},length(xContacts),1);repmat({'Offset'},length(xContacts),1)]);




g(1,1).stat_density();g(2,1).stat_density();g(3,1).stat_density();
g(1,2).stat_density();g(2,2).stat_density();g(3,2).stat_density();
g(1,3).stat_density();g(2,3).stat_density();g(3,3).stat_density();
g(1,1).no_legend; g(2,1).no_legend; g(3,1).no_legend
g(1,2).no_legend; g(2,2).no_legend; g(3,2).no_legend
g.axe_property('XLim',[-400 400]);
g.axe_property('YLim',[0 0.05]);


figure('Renderer', 'painters', 'Position', [100 100 800 400]);
g.draw();
