onsetTimes = [stoppingBeta.timing.canceled.mean_burstOnset+stoppingBeta.timing.canceled.mean_burstTime;...
stoppingBeta.timing.noncanceled.mean_burstOnset+stoppingBeta.timing.canceled.mean_burstTime;...
stoppingBeta.timing.nostop.mean_burstOnset+stoppingBeta.timing.nostop.mean_burstTime];

peakTimes = [stoppingBeta.timing.canceled.mean_burstTime;...
stoppingBeta.timing.canceled.mean_burstTime;...
stoppingBeta.timing.nostop.mean_burstTime];

offsetTimes = [stoppingBeta.timing.canceled.mean_burstOffset+stoppingBeta.timing.canceled.mean_burstTime;...
stoppingBeta.timing.noncanceled.mean_burstOffset+stoppingBeta.timing.canceled.mean_burstTime;...
stoppingBeta.timing.nostop.mean_burstOffset+stoppingBeta.timing.nostop.mean_burstTime];

inputTimes = [onsetTimes; peakTimes; offsetTimes];

epochLabels = [repmat({'Onset'},length(onsetTimes),1);...
    repmat({'Peak'},length(peakTimes),1);...
    repmat({'Offset'},length(offsetTimes),1)];

trlLabels = repmat([repmat({'Canceled'},509,1);...
    repmat({'Noncanceled'},509,1);...
    repmat({'No-Stop'},509,1)],3,1);

clear g
%Averages with confidence interval
g(1,1)= gramm('x',trlLabels,...
    'y',inputTimes,...
    'color',epochLabels);

g(1,1).stat_boxplot %('type','quartile','geom',{'point','black_errorbar'});

g(1,1).axe_property('XDir','Reverse');

g.coord_flip();
g(1,1).axe_property('YLim',[-400 400]);
% g(1,2).axe_property('YLim',[0.25 1]);
figure('Renderer', 'painters', 'Position', [100 100 500 300]);
g.draw();

